# fatigue/confs/training.yaml

job:
  KIND: TrainingJob

  # 1. Hyperparameters
  bootstrap: True
  max_depth: 7
  max_features: 'log2'
  min_samples_leaf: 2
  min_samples_split: 18
  n_estimators: 105
  # fatigue_threshold: 0.23

  # 2. Data Paths (Pointing to your processed data)
  inputs_train:
    KIND: ParquetReader
    path: data/processed/inputs_train.parquet

  targets_train:
    KIND: ParquetReader
    path: data/processed/targets_train.parquet

  # 3. Registry Settings
  run_config:
    name: "Fatigue_RF_Training"
    tags:
      project: "fatigue"
      model: "random_forest"

  mlflow_service:
    tracking_uri: "./mlruns"
    experiment_name: "Training"
