# https://docs.docker.com/compose/compose-file/

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.20.3
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_HOST=0.0.0.0
    # Mounting a volume so your experiments are saved even if you restart the container
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --backend-store-uri sqlite:///mlruns/mlflow.db --default-artifact-root /mlruns
